### ISSUE TITLE
gym.error.NameNotFound: Environment PDDLEnvTaskographyv2tiny10 doesn't exist. Did you mean: `PDDLEnvNavigation10`?

### ISSUE THREAD

**Issue by emoLeader** [taskography/scenegraph-planners#2]
Sorry, I don't know how to fix this error.

Collecting training data
Traceback (most recent call last):
  File "main.py", line 78, in <module>
    training_data = collect_training_data(
  File "/media/lzy/scenegraph-planners/ploi/datautils.py", line 35, in collect_training_data
    env = pddlgym.make(f"PDDLEnv{train_env_name}-v0")
  File "/home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/pddlgym/__init__.py", line 19, in make
    return gym.make(*args, disable_env_checker=True, **kwargs)
  File "/home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/gym/envs/registration.py", line 569, in make
    _check_version_exists(ns, name, version)
  File "/home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/gym/envs/registration.py", line 219, in _check_version_exists
    _check_name_exists(ns, name)
  File "/home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/gym/envs/registration.py", line 197, in _check_name_exists
    raise error.NameNotFound(
gym.error.NameNotFound: Environment PDDLEnvTaskographyv2tiny10 doesn't exist. Did you mean: `PDDLEnvNavigation10`?

**Comment by emoLeader** [comment]
> Sorry, I don't know how to fix this error.
> 
> Collecting training data Traceback (most recent call last): File "main.py", line 78, in training_data = collect_training_data( File "/media/lzy/scenegraph-planners/ploi/datautils.py", line 35, in collect_training_data env = pddlgym.make(f"PDDLEnv{train_env_name}-v0") File "/home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/pddlgym/**init**.py", line 19, in make return gym.make(*args, disable_env_checker=True, **kwargs) File "/home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/gym/envs/registration.py", line 569, in make _check_version_exists(ns, name, version) File "/home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/gym/envs/registration.py", line 219, in _check_version_exists _check_name_exists(ns, name) File "/home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/gym/envs/registration.py", line 197, in _check_name_exists raise error.NameNotFound( gym.error.NameNotFound: Environment PDDLEnvTaskographyv2tiny10 doesn't exist. Did you mean: `PDDLEnvNavigation10`?
