### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by emoLeader** [taskography/scenegraph-planners#3]
Thank you very much for sharing this code！！！
I just ran “python main.py --domain taskographyv2tiny10 --method ploi --num-train-problems 40 --epochs 401 --mode train  --timeout 30 --expid taskographyv2tiny10_ploi --logdir cache/results --all-problems”，but the following error occurred：

(taskography) lzy@ubuntu:/media/lzy/scenegraph-planners$ python main.py --domain taskographyv2tiny10 --method ploi --num-train-problems 40 --epochs 401 --mode train  --timeout 30 --expid taskographyv2tiny10_ploi --logdir cache/results --all-problems
/home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/torch_geometric/typing.py:54: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/libpyg.so)
  warnings.warn(f"An issue occurred while importing 'pyg-lib'. "
/home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/torch_geometric/typing.py:110: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/lzy/anaconda3/envs/taskography/lib/python3.8/site-packages/libpyg.so)
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Domain: Taskographyv2tiny10
Train planner: fd-lama-first
Test planner: fd-lama-first
Instantiating FD in SATISFICING mode
Instantiating FD in SATISFICING mode
Collecting training data
Training data already found on disk
Loading training data from file
Traceback (most recent call last):
  File "main.py", line 95, in <module>
    graphs_inp, graphs_tgt, graph_metadata = create_graph_dataset(training_data)
  File "/media/lzy/scenegraph-planners/ploi/datautils.py", line 238, in create_graph_dataset
    assert max(_node_feature_to_idx.values()) == nnf - 1
ValueError: max() arg is an empty sequence

**Comment by emoLeader** [comment]
**### planning failed**
python main.py --domain taskographyv2medium10scrub --method ploi --num-train-problems 40 --epochs 401 --mode train  --timeout 30 --expid taskographyv2medium10scrub_ploi --logdir cache/results-official --all-problems

Domain: Taskographyv2medium10scrub
Train planner: fd-lama-first
Test planner: fd-lama-first
Instantiating FD in SATISFICING mode
Instantiating FD in SATISFICING mode
Collecting training data
40 problems found!
Collecting training data for problem 0
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 0, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 1
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 1, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 2
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 2, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 3
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 3, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 4
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 4, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 5
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 5, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 6
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 6, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 7
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 7, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 8
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 8, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 9
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 9, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 10
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 10, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 11
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 11, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 12
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 12, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 13
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 13, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 14
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 14, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 15
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 15, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 16
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 16, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 17
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 17, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 18
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 18, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 19
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 19, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 20
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 20, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 21
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 21, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 22
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 22, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 23
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 23, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 24
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 24, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 25
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 25, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 26
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 26, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 27
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 27, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 28
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 28, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 29
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 29, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 30
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 30, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 31
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 31, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 32
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 32, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 33
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 33, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 34
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 34, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 35
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 35, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 36
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 36, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 37
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 37, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 38
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 38, env.problems[idx].fname
  warnings.warn(
Collecting training data for problem 39
/home/lzy/scenegraph-planners/ploi/datautils.py:47: UserWarning: Planning failed. Skipping problem 39, env.problems[idx].fname
  warnings.warn(
Loading training data from file
Traceback (most recent call last):
  File "main.py", line 95, in <module>
    graphs_inp, graphs_tgt, graph_metadata = create_graph_dataset(training_data)
  File "/home/lzy/scenegraph-planners/ploi/datautils.py", line 238, in create_graph_dataset
    assert max(_node_feature_to_idx.values()) == nnf - 1
ValueError: max() arg is an empty sequence
